### ISSUE TITLE
How to use the trained models?

### ISSUE THREAD

**Issue by GabrielLin** [sciosci/cite-worthiness#1]
Could you please tell me how to use the trained models for judging whether a given text should cite or not? And how to evaluate a trained model? Thanks.

**Comment by tong-zeng** [comment]
Hi Lin,

Thank you for your interest, as we use allennlp to facilitate the development of deep learning models, for some standard operations like `train`, `predict` and `evaluate` are depends on allennlp. Please refer to the allennlp  [predict](https://docs.allennlp.org/v0.9.0/api/allennlp.commands.predict.html) and [evaluate](https://docs.allennlp.org/v0.9.0/api/allennlp.commands.evaluate.html) command for the model  prediction and evaluation. Thanks.

**Comment by GabrielLin** [comment]
Dear @tong-zeng , thanks for your reply. Let me try it.
